interface GameAccountsList {
  gameId: string;
  title: string;
  icon: string;
  cover: string;
  link: string;
}

const GameAccountsLists: GameAccountsList[] = [
  { 
    gameId: '1',
    title: '8 Ball Pool',
    icon: 'https://play-lh.googleusercontent.com/bPz1guJ6FHF3oIOEy3KqwpaDDKO-hLRaZoyzmM8bLFLN8fWm6L0_EuUnkwv9iqPo3Ag',
    cover: 'https://rare-gallery.com/uploads/posts/387947-4k-wallpaper.jpg',
    link: '/shop/1',
  },
  { 
    gameId: '2',
    title: 'Activision',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/activision.png',
    cover: 'https://rare-gallery.com/mocahbig/452712-Call-of-Duty-Modern-Warfare-3-video-games-Call-of.jpg',
    link: '/shop/2',
  },
  { 
    gameId: '3',
    title: 'Apex Legends',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/apex-legends.png',
    cover: 'https://images.hdqwalls.com/wallpapers/4k-apex-legends-2020-ja.jpg',
    link: '/shop/3',
  },
  { 
    gameId: '4',
    title: 'ARK: Survival Evolved',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/ark-survival-evolved.png',
    cover: 'https://cdn.mos.cms.futurecdn.net/8KkMA3ZGrp222WMKZCNPiK.jpg',
    link: '/shop/4',
  },
  { 
    gameId: '5',
    title: 'Battlenet',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/battlenet.png',
    cover: 'https://multiplayer.net-cdn.it/thumbs/images/2022/08/01/activision_blizzard_jpeg_1600x900_crop_q85.jpg',
    link: '/shop/5',
  },
  { 
    gameId: '6',
    title: 'Black Desert Online',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/black-desert-online.png',
    cover: 'https://www.slantmagazine.com/wp-content/uploads/2016/03/blackdesertonline.jpg',
    link: '/shop/6',
  },
  { 
    gameId: '7',
    title: 'Bleach: Brave Souls',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/bleach-brave-souls.png',
    cover: 'https://4kwallpapers.com/images/wallpapers/ichigo-kurosaki-3840x2160-10502.jpg',
    link: '/shop/7',
  },
  { 
    gameId: '8',
    title: 'Brawl Stars',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/brawl-stars.png',
    cover: 'https://images5.alphacoders.com/127/1279150.jpg',
    link: '/shop/8',
  },
  { 
    gameId: '9',
    title: 'Call of Duty',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/call-of-duty.png',
    cover: 'https://images.hdqwalls.com/wallpapers/call-of-duty-modern-warfare-4k-wz.jpg',
    link: '/shop/9',
  },
  { 
    gameId: '10',
    title: 'Call of Duty Mobile',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/call-of-duty-mobile.png',
    cover: 'https://images.hdqwalls.com/wallpapers/call-of-duty-mobile-4k-game-2b.jpg',
    link: '/shop/10',
  },
  { 
    gameId: '11',
    title: 'Clash of Clans',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/clash-of-clans.png',
    cover: 'https://www.pixel4k.com/wp-content/uploads/2021/03/clash-royale-clan-wars-4k_1614860779.jpg',
    link: '/shop/11',
  },
  { 
    gameId: '12',
    title: 'Clash Royale',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/clash-royale.png',
    cover: 'https://images.hdqwalls.com/wallpapers/eggoblins-clash-royale-4k-4x.jpg',
    link: '/shop/12',
  },
  { 
    gameId: '13',
    title: 'Counter-Strike 2',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/counter-strike-2.png',
    cover: 'https://rare-gallery.com/uploads/posts/344274-CSGO-Counter-Strike-Global-Offensive-Video-Game-AK-47-Counter-Terrorist.jpg',
    link: '/shop/13',
  },
  { 
    gameId: '14',
    title: 'Counter-Strike: Global Offensive',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/csgo.png',
    cover: 'https://images.hdqwalls.com/wallpapers/counter-strike-global-offensive-4k-new-af.jpg',
    link: '/shop/14',
  },
  { 
    gameId: '15',
    title: 'DayZ',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dayz.png',
    cover: 'https://image.api.playstation.com/vulcan/ap/rnd/202301/0312/9oKyhaUOZTJYI6Pk6yNPKvGS.jpg',
    link: '/shop/15',
  },
  { 
    gameId: '16',
    title: 'Dead By Daylight',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dead-by-daylight.png',
    cover: 'https://rare-gallery.com/uploads/posts/344298-Dead-by-Daylight-Video-Game-The-Nurse-Sally-Smithson.jpg',
    link: '/shop/16',
  },
  { 
    gameId: '17',
    title: 'Destiny 2',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/destiny-2.png',
    cover: 'https://rare-gallery.com/mocahbig/392394-destiny-2-exo-stranger-4k-pc-wallpaper.jpg',
    link: '/shop/17',
  },
  { 
    gameId: '18',
    title: 'Diablo 2: Resurrected',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/diablo-2-resurrected.png',
    cover: 'https://images5.alphacoders.com/113/1132616.jpg',
    link: '/shop/18',
  },
  { 
    gameId: '19',
    title: 'Diablo 4',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/diablo-4.png',
    cover: 'https://images.hdqwalls.com/wallpapers/2022-diablo-iv-necromancer-4k-tt.jpg',
    link: '/shop/19',
  },
  { 
    gameId: '20',
    title: 'Diablo Immortal',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/diablo-immortal.png',
    cover: 'https://images8.alphacoders.com/112/1126804.jpg',
    link: '/shop/20',
  },
  { 
    gameId: '21',
    title: 'Dota 2',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dota-2.png',
    cover: 'https://images2.alphacoders.com/479/479565.jpg',
    link: '/shop/21',
  },
  { 
    gameId: '22',
    title: 'Dragon Ball Legends',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dragon-ball-legends.png',
    cover: 'https://i.redd.it/dd1oybjtjct51.png',
    link: '/shop/22',
  },
  { 
    gameId: '23',
    title: 'Elden Ring',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/elden-ring.png',
    cover: 'https://images.alphacoders.com/121/1216678.jpg',
    link: '/shop/23',
  },
  { 
    gameId: '24',
    title: 'Elder Scrolls Online',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/elder-scrolls-online.png',
    cover: 'https://images.hdqwalls.com/wallpapers/the-elder-scrolls-online-4k-5m.jpg',
    link: '/shop/24',
  },
  { 
    gameId: '25',
    title: 'Epic Games',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/epic-games.png',
    cover: 'https://wallpaperaccess.com/full/117111.jpg',
    link: '/shop/25',
  },
  { 
    gameId: '26',
    title: 'Epic Seven',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/epic-seven.png',
    cover: 'https://images2.alphacoders.com/118/1186510.jpg',
    link: '/shop/26',
  },
  { 
    gameId: '27',
    title: 'Escape From Tarkov',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/escape-from-tarkov.png',
    cover: 'https://i.imgur.com/ctvSiZk.jpg',
    link: '/shop/27',
  },
  { 
    gameId: '28',
    title: 'EVE Online',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/eve-online.png',
    cover: 'https://images4.alphacoders.com/116/1160594.jpg',
    link: '/shop/28',
  },
  { 
    gameId: '29',
    title: 'Fallout 76',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fallout-76.png',
    cover: 'https://images7.alphacoders.com/927/thumb-1920-927080.jpg',
    link: '/shop/29',
  },
  { 
    gameId: '30',
    title: 'Fate/Grand Order',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fategrand-order.png',
    cover: 'https://pixelz.cc/wp-content/uploads/2019/02/fate-grand-order-saber-uhd-4k-wallpaper.jpg',
    link: '/shop/30',
  },
  { 
    gameId: '31',
    title: 'FIFA',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fifa.png',
    cover: 'https://gameranx.com/wp-content/uploads/2016/06/FIFA-17-1080P-Wallpaper.jpg',
    link: '/shop/31',
  },
  { 
    gameId: '32',
    title: 'FIFA Mobile',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fifa-mobile.png',
    cover: 'https://rare-gallery.com/mocahbig/392947-fifa-22-football-game-football-game-4k-pc-wallpaper.jpg',
    link: '/shop/32',
  },
  { 
    gameId: '33',
    title: 'Final Fantasy XIV',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/final-fantasy-xiv.png',
    cover: 'https://i.pinimg.com/originals/aa/ed/09/aaed09359bcca1262f923b1c3519eab4.jpg',
    link: '/shop/33',
  },
  { 
    gameId: '34',
    title: 'Fortnite',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fortnite.png',
    cover: 'https://cdn.wallpapersafari.com/20/62/dUiqAo.jpg',
    link: '/shop/34',
  },
  { 
    gameId: '35',
    title: 'Forza Horizon 5',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/forza-horizon-5.png',
    cover: 'https://4kwallpapers.com/images/wallpapers/forza-horizon-5-xbox-series-x-and-series-s-xbox-one-pc-3840x2160-7579.jpg',
    link: '/shop/35',
  },
  { 
    gameId: '36',
    title: 'Garena Free Fire',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/garena-free-fire.png',
    cover: 'https://wallpapercave.com/wp/wp7707325.jpg',
    link: '/shop/36',
  },
  { 
    gameId: '37',
    title: 'Genshin Impact',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/genshin-impact.png',
    cover: 'https://i.pinimg.com/originals/97/f4/0e/97f40e0eacbabc3734a54bc6a27eb508.jpg',
    link: '/shop/37',
  },
  { 
    gameId: '38',
    title: 'Grand Theft Auto 5',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/gta-5.png',
    cover: 'https://wallpaperaccess.com/full/707055.jpg',
    link: '/shop/38',
  },
  { 
    gameId: '39',
    title: 'Hay Day',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/hay-day.png',
    cover: 'https://cdna.artstation.com/p/assets/images/images/034/073/374/4k/studio-pinata-landscape01.jpg?1611320880',
    link: '/shop/39',
  },
  { 
    gameId: '40',
    title: 'Honkai: Star Rail',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/honkai-star-rail.png',
    cover: 'https://wallpapercave.com/wp/wp12342724.jpg',
    link: '/shop/40',
  },
  { 
    gameId: '41',
    title: 'IMVU',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/imvu.png',
    cover: 'https://i.ibb.co/x5d1sQH/imvu.jpg',
    link: '/shop/41',
  },
  { 
    gameId: '42',
    title: 'League of Legends',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/league-of-legends.png',
    cover: 'https://images.hdqwalls.com/wallpapers/2020-4k-league-of-legends-e8.jpg',
    link: '/shop/42',
  },
  { 
    gameId: '43',
    title: 'League of Legends: Wild Rift',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/league-of-legends-wild-rift.png',
    cover: 'https://www.xtrafondos.com/en/descargar.php?id=6494&resolucion=2560x1440',
    link: '/shop/43',
  },
  { 
    gameId: '44',
    title: 'Lords Mobile',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/lords-mobile.png',
    cover: 'https://images.hdqwalls.com/wallpapers/lords-mobile-kingdom-wars-2023-2z.jpg',
    link: '/shop/44',
  },
  { 
    gameId: '45',
    title: 'Lost Ark',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/lost-ark.png',
    cover: 'https://rare-gallery.com/mocahbig/394261-lost-ark-mmorpg-game-warrior-destroyer-4k-pc.jpg',
    link: '/shop/45',
  },
  { 
    gameId: '46',
    title: 'Minecraft',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/minecraft.png',
    cover: 'https://images6.alphacoders.com/108/1082090.jpg',
    link: '/shop/46',
  },
  { 
    gameId: '47',
    title: 'Mobile Legends',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/mobile-legends.png',
    cover: 'https://images.hdqwalls.com/wallpapers/4k-mobile-legends-2b.jpg',
    link: '/shop/47',
  },
  { 
    gameId: '48',
    title: 'NBA 2K',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/nba.png',
    cover: 'https://wallpaperaccess.com/full/1440418.jpg',
    link: '/shop/48',
  },
  { 
    gameId: '49',
    title: 'New World',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/new-world.png',
    cover: 'https://www.pcgamesn.com/wp-content/sites/pcgamesn/2021/10/New-World_Best_Settings_PC_Performance-1.jpg',
    link: '/shop/49',
  },
  { 
    gameId: '50',
    title: 'Old School RuneScape',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/osrs.png',
    cover: 'https://wallpapercave.com/wp/wp8628975.png',
    link: '/shop/50',
  },
  { 
    gameId: '51',
    title: 'One Piece Bounty Rush',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/one-piece-bounty-rush.png',
    cover: 'https://wallpaperaccess.com/full/2606711.jpg',
    link: '/shop/51',
  },
  { 
    gameId: '52',
    title: 'Origin',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/origin.png',
    cover: 'https://images.hdqwalls.com/wallpapers/assassins-creed-origins-game-4k-4m.jpg',
    link: '/shop/52',
  },
  { 
    gameId: '53',
    title: 'Overwatch 2',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/overwatch-2.png',
    cover: 'https://pixelz.cc/wp-content/uploads/2019/12/overwatch-2-characters-uhd-4k-wallpaper.jpg',
    link: '/shop/53',
  },
  { 
    gameId: '54',
    title: 'Path of Exile',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/path-of-exile.png',
    cover: 'https://www.pixel4k.com/wp-content/uploads/2018/11/path-of-exile-ascendancy-4k_1542494947.jpg',
    link: '/shop/54',
  },
  { 
    gameId: '55',
    title: 'PlayStation',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/playstation.png',
    cover: 'https://images4.alphacoders.com/130/1303457.jpg',
    link: '/shop/55',
  },
  { 
    gameId: '56',
    title: 'Pokemon Go',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/pokemon-go.png',
    cover: 'https://images8.alphacoders.com/962/962548.jpg',
    link: '/shop/56',
  },
  { 
    gameId: '57',
    title: 'PUBG',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/playerunknowns-battlegrounds.png',
    cover: 'https://wallpaperaccess.com/full/825336.jpg',
    link: '/shop/57',
  },
  { 
    gameId: '58',
    title: 'PUBG Mobile',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/pubg-mobile.png',
    cover: 'https://4kwallpapers.com/images/wallpapers/pubg-mobile-playerunknowns-battlegrounds-5k-1920x1080-8280.jpg',
    link: '/shop/58',
  },
  { 
    gameId: '59',
    title: 'Raid: Shadow Legends',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/raid-shadow-legends.png',
    cover: 'https://wallpapercave.com/wp/wp7030218.jpg',
    link: '/shop/59',
  },
  { 
    gameId: '60',
    title: 'Rainbow Six Siege',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rainbow-six-siege.png',
    cover: 'https://images.hdqwalls.com/wallpapers/4k-tom-clancys-rainbow-six-siege-game-27.jpg',
    link: '/shop/60',
  },
  { 
    gameId: '61',
    title: 'Red Dead Redemption 2',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/red-dead-redemption-2.png',
    cover: 'https://wallpapercrafter.com/desktop/84468-red-dead-redemption-2-4k-2018-games-games-hd-ps-games-deviantart.jpg',
    link: '/shop/61',
  },
  { 
    gameId: '62',
    title: 'Rise of Kingdoms',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rise-of-kingdoms.png',
    cover: 'https://rok.guide/wp-content/uploads/2021/01/rok-wallpaper-18.jpg',
    link: '/shop/62',
  },
  { 
    gameId: '63',
    title: 'Roblox',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/roblox.png',
    cover: 'https://images7.alphacoders.com/121/1217519.jpg',
    link: '/shop/63',
  },
  { 
    gameId: '64',
    title: 'Rocket League',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rocket-league.png',
    cover: 'https://rocketleague.media.zestyio.com/rl_gen_blog_1920x1080.jpg',
    link: '/shop/64',
  },
  { 
    gameId: '65',
    title: 'RuneScape 3',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/runescape-3.png',
    cover: 'https://images4.alphacoders.com/984/984544.jpg',
    link: '/shop/65',
  },
  { 
    gameId: '66',
    title: 'Rust',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rust.png',
    cover: 'https://rare-gallery.com/mocahbig/397663-wallpaper-rust-game-hazmat-suit-4k-hd.jpg',
    link: '/shop/66',
  },
  { 
    gameId: '67',
    title: 'Sea of Thieves',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/sea-of-thieves.png',
    cover: 'https://rare-gallery.com/uploads/posts/522312-sea-of-thieves.jpg',
    link: '/shop/67',
  },
  { 
    gameId: '68',
    title: 'Steam',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/steam.png',
    cover: 'https://images3.alphacoders.com/693/thumb-1920-693872.jpg',
    link: '/shop/68',
  },
  { 
    gameId: '69',
    title: 'Summoners War',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/summoners-war.png',
    cover: 'https://cdn.wallpapersafari.com/40/41/Mb50Hz.jpg',
    link: '/shop/69',
  },
  { 
    gameId: '70',
    title: 'Tower of Fantasy',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/tower-of-fantasy.png',
    cover: 'https://images.alphacoders.com/120/1209436.jpg',
    link: '/shop/70',
  },
  { 
    gameId: '71',
    title: 'Ubisoft Connect',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/ubisoft-connect.png',
    cover: 'https://www.psu.com/wp/wp-content/uploads/2020/10/WatchDogsLegion-5-1.jpg',
    link: '/shop/71',
  },
  { 
    gameId: '72',
    title: 'Valheim',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/valheim.png',
    cover: 'https://free4kwallpapers.com/uploads/originals/2022/12/01/valheim-wallpaper.jpg',
    link: '/shop/72',
  },
  { 
    gameId: '73',
    title: 'Valorant',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/valorant.png',
    cover: 'https://wallpapers.com/images/featured/305kescxw5dpup7y.jpg',
    link: '/shop/73',
  },
  { 
    gameId: '74',
    title: 'War Thunder',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/war-thunder.png',
    cover: 'https://images3.alphacoders.com/112/1125182.jpg',
    link: '/shop/74',
  },
  { 
    gameId: '75',
    title: 'Warframe',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/warframe.png',
    cover: 'https://external-preview.redd.it/SagoGS-OmCQsmX_r2stalvAeG7eQ-9ohRnIQ0pnD0ic.jpg?auto=webp&s=2e527672bcee6cf8b0f0647248e7fbd1bd8aab77',
    link: '/shop/75',
  },
  { 
    gameId: '76',
    title: 'World of Warcraft',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/world-of-warcraft.png',
    cover: 'https://images.hdqwalls.com/wallpapers/world-of-warcraft-shadowlands-2021-4k-b4.jpg',
    link: '/shop/76',
  },
  { 
    gameId: '77',
    title: 'WoW WotLK',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/world-of-warcraft-wotlk.png',
    cover: 'https://wow.zamimg.com/uploads/screenshots/normal/1059910.jpg',
    link: '/shop/77',
  },
  { 
    gameId: '78',
    title: 'Xbox',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/xbox.png',
    cover: 'https://wallpapers.com/images/featured/roz8agvfa6wdkxav.jpg',
    link: '/shop/78',
  },
  { 
    gameId: '79',
    title: 'XDefiant',
    icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/xdefiant.png',
    cover: 'https://rare-gallery.com/mocahbig/393469-xdefiant-tom-clancys-game-echelon-faction-4k-pc.jpg',
    link: '/shop/79',
  },
]

export default GameAccountsLists;