interface GameAccountsList {
  title: string;
  icon: string;
}

const GameAccountsLists: GameAccountsList[] = [
  { title: '8 Ball Pool', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/8-ball-pool.png?w=28&h=28&q=40' },
  { title: 'Activision', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/activision.png?w=28&h=28&q=40' },
  { title: 'Apex Legends', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/apex-legends.png?w=28&h=28&q=40' },
  { title: 'ARK: Survival Evolved', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/ark-survival-evolved.png?w=28&h=28&q=40' },
  { title: 'Battlenet', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/battlenet.png?w=28&h=28&q=40' },
  { title: 'Black Desert Online', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/black-desert-online.png?w=28&h=28&q=40' },
  { title: 'Bleach: Brave Souls', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/bleach-brave-souls.png?w=28&h=28&q=40' },
  { title: 'Brawl Stars', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/brawl-stars.png?w=28&h=28&q=40' },
  { title: 'Call of Duty', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/call-of-duty.png?w=28&h=28&q=40' },
  { title: 'Call of Duty Mobile', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/call-of-duty-mobile.png?w=28&h=28&q=40' },
  { title: 'Clash of Clans', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/clash-of-clans.png?w=28&h=28&q=40' },
  { title: 'Clash Royale', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/clash-royale.png?w=28&h=28&q=40' },
  { title: 'Counter-Strike 2', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/counter-strike-2.png?w=28&h=28&q=40' },
  { title: 'Counter-Strike: Global Offensive', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/csgo.png?w=28&h=28&q=40' },
  { title: 'DayZ', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dayz.png?w=28&h=28&q=40' },
  { title: 'Dead By Daylight', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dead-by-daylight.png?w=28&h=28&q=40' },
  { title: 'Destiny 2', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/destiny-2.png?w=28&h=28&q=40' },
  { title: 'Diablo 2: Resurrected', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/diablo-2-resurrected.png?w=28&h=28&q=40' },
  { title: 'Diablo 4', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/diablo-4.png?w=28&h=28&q=40' },
  { title: 'Diablo Immortal', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/diablo-immortal.png?w=28&h=28&q=40' },
  { title: 'Dota 2', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dota-2.png?w=28&h=28&q=40' },
  { title: 'Dragon Ball Legends', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/dragon-ball-legends.png?w=28&h=28&q=40' },
  { title: 'Elden Ring', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/elden-ring.png?w=28&h=28&q=40' },
  { title: 'Elder Scrolls Online', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/elder-scrolls-online.png?w=28&h=28&q=40' },
  { title: 'Epic Games', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/epic-games.png?w=28&h=28&q=40' },
  { title: 'Epic Seven', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/epic-seven.png?w=28&h=28&q=40' },
  { title: 'Escape From Tarkov', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/escape-from-tarkov.png?w=28&h=28&q=40' },
  { title: 'EVE Online', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/eve-online.png?w=28&h=28&q=40' },
  { title: 'Fallout 76', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fallout-76.png?w=28&h=28&q=40' },
  { title: 'Fate/Grand Order', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fategrand-order.png?w=28&h=28&q=40' },
  { title: 'FIFA', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fifa.png?w=28&h=28&q=40' },
  { title: 'FIFA Mobile', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fifa-mobile.png?w=28&h=28&q=40' },
  { title: 'Final Fantasy XIV', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/final-fantasy-xiv.png?w=28&h=28&q=40' },
  { title: 'Fortnite', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/fortnite.png?w=28&h=28&q=40' },
  { title: 'Forza Horizon 5', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/forza-horizon-5.png?w=28&h=28&q=40' },
  { title: 'Garena Free Fire', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/garena-free-fire.png?w=28&h=28&q=40' },
  { title: 'Genshin Impact', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/genshin-impact.png?w=28&h=28&q=40' },
  { title: 'Grand Theft Auto 5', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/gta-5.png?w=28&h=28&q=40' },
  { title: 'Hay Day', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/hay-day.png?w=28&h=28&q=40' },
  { title: 'Honkai: Star Rail', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/honkai-star-rail.png?w=28&h=28&q=40' },
  { title: 'IMVU', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/imvu.png?w=28&h=28&q=40' },
  { title: 'League of Legends', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/league-of-legends.png?w=28&h=28&q=40' },
  { title: 'League of Legends: Wild Rift', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/league-of-legends-wild-rift.png?w=28&h=28&q=40' },
  { title: 'Lords Mobile', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/lords-mobile.png?w=28&h=28&q=40' },
  { title: 'Lost Ark', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/lost-ark.png?w=28&h=28&q=40' },
  { title: 'Minecraft', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/minecraft.png?w=28&h=28&q=40' },
  { title: 'Mobile Legends', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/mobile-legends.png?w=28&h=28&q=40' },
  { title: 'NBA', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/nba.png?w=28&h=28&q=40' },
  { title: 'New World', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/new-world.png?w=28&h=28&q=40' },
  { title: 'Old School RuneScape', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/osrs.png?w=28&h=28&q=40' },
  { title: 'One Piece Bounty Rush', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/one-piece-bounty-rush.png?w=28&h=28&q=40' },
  { title: 'Origin', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/origin.png?w=28&h=28&q=40' },
  { title: 'Overwatch 2', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/overwatch-2.png?w=28&h=28&q=40' },
  { title: 'Path of Exile', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/path-of-exile.png?w=28&h=28&q=40' },
  { title: 'PlayStation', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/playstation.png?w=28&h=28&q=40' },
  { title: 'Pokemon Go', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/pokemon-go.png?w=28&h=28&q=40' },
  { title: 'PUBG', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/playerunknowns-battlegrounds.png?w=28&h=28&q=40' },
  { title: 'PUBG Mobile', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/pubg-mobile.png?w=28&h=28&q=40' },
  { title: 'Raid: Shadow Legends', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/raid-shadow-legends.png?w=28&h=28&q=40' },
  { title: 'Rainbow Six Siege', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rainbow-six-siege.png?w=28&h=28&q=40' },
  { title: 'Red Dead Redemption 2', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/red-dead-redemption-2.png?w=28&h=28&q=40' },
  { title: 'Rise of Kingdoms', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rise-of-kingdoms.png?w=28&h=28&q=40' },
  { title: 'Roblox', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/roblox.png?w=28&h=28&q=40' },
  { title: 'Rocket League', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rocket-league.png?w=28&h=28&q=40' },
  { title: 'RuneScape 3', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/runescape-3.png?w=28&h=28&q=40' },
  { title: 'Rust', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/rust.png?w=28&h=28&q=40' },
  { title: 'Sea of Thieves', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/sea-of-thieves.png?w=28&h=28&q=40' },
  { title: 'Steam', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/steam.png?w=28&h=28&q=40' },
  { title: 'Summoners War', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/summoners-war.png?w=28&h=28&q=40' },
  { title: 'Tower of Fantasy', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/tower-of-fantasy.png?w=28&h=28&q=40' },
  { title: 'Ubisoft Connect', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/ubisoft-connect.png?w=28&h=28&q=40' },
  { title: 'Valheim', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/valheim.png?w=28&h=28&q=40' },
  { title: 'Valorant', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/valorant.png?w=28&h=28&q=40' },
  { title: 'War Thunder', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/war-thunder.png?w=28&h=28&q=40' },
  { title: 'Warframe', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/warframe.png?w=28&h=28&q=40' },
  { title: 'World of Warcraft', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/world-of-warcraft.png?w=28&h=28&q=40' },
  { title: 'WoW WotLK', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/world-of-warcraft-wotlk.png?w=28&h=28&q=40' },
  { title: 'Xbox', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/xbox.png?w=28&h=28&q=40' },
  { title: 'XDefiant', icon: 'https://assetsdelivery.eldorado.gg/v7/_assets_/icons/v13/xdefiant.png?w=28&h=28&q=40' },
]

export default GameAccountsLists;